# Generated by Django 3.2.3 on 2021-09-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proyectos',
            new_name='Proyecto',
        ),
    ]
