# Generated by Django 3.2.3 on 2021-09-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_rename_proyectos_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='descripcion_cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='estudios_cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_entrada', models.DateField()),
                ('anio_finalizacion', models.DateField()),
                ('nombre_curso', models.CharField(max_length=50)),
                ('academia', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='experiencias_cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_entrada', models.DateField()),
                ('anio_finalizacion', models.DateField()),
                ('nombre_cargo', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
