# Generated by Django 3.2.3 on 2021-09-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_descripcion_cv_estudios_cv_experiencias_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_cv',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
