# Generated by Django 3.2.3 on 2021-09-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_descripcion_cv_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios_cv',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencias_cv',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
